import { useEffect, useState } from 'react'
import { ArrowRight, Crosshair, Shield, Swords } from 'lucide-react'
import { clock, heroImage, type Match } from './data'
import { abilityImage, itemImage } from './locale'
import { fightDetail, mapPosition } from './fightDetail'
import { sideLabel, signed } from './review'
import mapImage from './dota-map.webp'
import { MatchPlayerName } from './MatchPlayerName'

export function FightBreakdown({ match, selectedIndex, onSelect }: { match: Match; selectedIndex?: number; onSelect: (index: number) => void }) {
  const [localIndex, setLocalIndex] = useState(0)
  useEffect(() => { setLocalIndex(0) }, [match.match_id])
  const indices = (match.teamfights || []).map((fight, index) => ({ fight, index })).filter(({ fight }) => fight.start >= 0)
  if (!indices.length) return <section id="match-fights" className="fight-breakdown"><div className="section-heading"><div><span className="section-index">TEAM FIGHTS</span><h2>团战复盘</h2></div></div><div className="fight-empty"><Shield size={18}/> 这场比赛没有已解析的团战明细。提交解析请求并刷新后可查看。</div></section>
  const active = indices.find(({ index }) => index === selectedIndex)?.index ?? indices.find(({ index }) => index === localIndex)?.index ?? indices[0].index
  const detail = fightDetail(match, active)!
  const choose = (index: number) => { setLocalIndex(index); onSelect(index) }
  const maxima = { damage: Math.max(1, ...detail.participants.map(p => p.damage)), healing: Math.max(1, ...detail.participants.map(p => p.healing)), gold: Math.max(1, ...detail.participants.map(p => Math.abs(p.gold))), xp: Math.max(1, ...detail.participants.map(p => Math.abs(p.xp))) }
  const stat = (value: number, kind: 'damage' | 'healing' | 'gold' | 'xp') => <span className="fight-stat"><span>{kind === 'gold' || kind === 'xp' ? signed(value) : value.toLocaleString('zh-CN')}</span><i className={value < 0 ? 'negative' : kind} style={{ width: `${Math.max(0, Math.abs(value) / maxima[kind] * 100)}%` }}/></span>
  return <section id="match-fights" className="fight-breakdown" aria-label="团战复盘">
    <div className="section-heading"><div><span className="section-index">TEAM FIGHTS / 团战明细</span><h2>团战复盘 <span className="count">{indices.length} 场</span></h2><p>选择一场团战，查看两队逐人损益、已记录的技能与物品使用，以及死亡位置。</p></div></div>
    <div className="fight-selector" role="group" aria-label="选择团战">{indices.map(({ fight, index }) => <button type="button" key={index} className={active === index ? 'active' : ''} aria-pressed={active === index} onClick={() => choose(index)}><small>第 {index + 1} 场</small><strong>{clock(fight.start)}</strong><span>{clock(fight.end)}</span></button>)}</div>
    <div className="fight-focus"><div className="fight-map-column"><div className="fight-map" role="img" aria-label={`团战 ${clock(detail.start)} 至 ${clock(detail.end)} 的已记录死亡位置`}><img src={mapImage} alt="Dota 2 地图" />{detail.positions.map((pos, index) => <span key={`${pos.slot}-${pos.x}-${pos.y}-${index}`} className={`fight-map-death ${pos.slot < 128 ? 'radiant' : 'dire'}`} style={mapPosition(pos.x, pos.y)} title={`${sideLabel(pos.slot < 128 ? 'radiant' : 'dire')} ${pos.hero} · 此处记录阵亡 ${pos.count} 次`} aria-hidden="true">×</span>)}</div><div className="fight-map-legend"><span><i className="radiant"/> 天辉死亡</span><span><i className="dire"/> 夜魇死亡</span></div><div className="fight-outcome"><strong>{clock(detail.start)} – {clock(detail.end)}</strong><span>阵亡 天辉 {detail.radiantDeaths} / 夜魇 {detail.direDeaths}</span><span>团战经济变化 天辉 {signed(detail.radiantGold)} · 夜魇 {signed(detail.direGold)}</span><span>团战经验变化 天辉 {signed(detail.radiantXp)} · 夜魇 {signed(detail.direXp)}</span></div>{detail.objectives.length ? <div className="fight-objectives"><strong>结束后 3 分钟内的目标</strong>{detail.objectives.map((o, i) => <span key={`${o.time}-${i}`}>{o.time} · {o.side ? sideLabel(o.side) : '阵营未知'} {o.label}</span>)}</div> : <p className="fight-no-objectives">结束后 3 分钟内没有已记录的主要目标。</p>}</div>
    <div className="fight-tables">{([['radiant', '天辉', detail.radiant], ['dire', '夜魇', detail.dire]] as const).map(([side, label, players]) => <div className="fight-team" key={side}><h3><Swords size={17}/>{label} · 团战 <span>阵亡 {side === 'radiant' ? detail.radiantDeaths : detail.direDeaths}</span></h3><div className="fight-table-scroll"><table className="fight-table"><thead><tr><th>玩家</th><th>死亡</th><th>伤害</th><th>治疗</th><th>经济</th><th>经验</th><th>技能使用</th><th>物品使用</th></tr></thead><tbody>{players.map(p => <tr key={p.slot}><td><div className="fight-person"><img src={heroImage(p.player.hero_id)} alt="" loading="lazy"/><span><MatchPlayerName player={p.player}/><small>{p.hero}</small></span></div></td><td className={p.deaths ? 'fight-dead' : ''}>{p.deaths || '—'}</td><td>{stat(p.damage, 'damage')}</td><td>{stat(p.healing, 'healing')}</td><td>{stat(p.gold, 'gold')}</td><td>{stat(p.xp, 'xp')}</td><td><div className="fight-usage">{p.abilities.map(a => <span key={a.key} title={`${a.name} · 使用 ${a.count} 次`}><img src={abilityImage(a.key)} alt="" loading="lazy" onError={e => { e.currentTarget.style.display = 'none' }}/><small>{a.name} ×{a.count}</small></span>)}{!p.abilities.length && '—'}</div></td><td><div className="fight-usage">{p.items.map(item => <span key={item.key} title={`${item.name} · 使用 ${item.count} 次`}><img src={itemImage(item.key)} alt="" loading="lazy" onError={e => { e.currentTarget.style.display = 'none' }}/><small>{item.name} ×{item.count}</small></span>)}{!p.items.length && '—'}</div></td></tr>)}</tbody></table></div></div>)}</div></div>
    <a className="fight-analyze-link" href="#match-ai" onClick={() => choose(active)}>用 AI 分析这场团战 <ArrowRight size={15}/></a>
    <p className="fight-caveat"><Crosshair size={15}/>{detail.positions.length ? `地图仅标出 ${detail.positions.reduce((n, p) => n + p.count, 0)} 次有坐标的死亡；没有坐标的阵亡不会出现在地图上。` : '此场团战没有死亡坐标，地图不绘制推测位置。'} {detail.explanation} <ArrowRight size={13}/></p>
  </section>
}
